export { Preloader } from './Preloader';
export { Hero } from './Hero';
export { About } from './About';
export { Skills } from './Skills';
export { Projects } from './Projects';
export { Experience } from './Experience';
export { Interests } from './Interests';
export { Contact } from './Contact';
export { Footer } from './Footer';
